// src/components/coolpeople.vue

<template>
    <div id="coolpeoplecontainer">
        <div id="coolpeople">
            <h1 id="coolkidstitle">COOL KIDS LIST</h1>
            <p class="opacity-70" id="coolpeopledesc">a list of people that have helped in the making of this website (or they're just that cool)</p>
            <ul>
                <li class="coolpersonlist" id="0">Ethan Edwards - came up with the idea for this website</li>
                <li class="coolpersonlist" id="1">Jacob Jackson - Various QOL ideas</li>
                <li class="coolpersonlist" id="2">Easton Snow - identified mobile bug for this very page</li>
                <li class="coolpersonlist" id="3">Isaiah Williams - idea of calendar widget</li>
            </ul>
        </div>
        <p id="joketext" class="opacity-25">this list is all inclusive. if ur not on it, im sorry for your loss.</p>
    </div>
</template>

<style>
    @tailwind base;
    @tailwind components;
    @tailwind utilities;
    #coolpeople {
        font-family: "Comic Sans MS", "Comic Sans", cursive;
        display: flex;
        justify-content: center;
        flex-direction: column;
        align-items: center;
    }
    #joketext {
        text-align: center;
    }
    #coolpeopledesc, .coolpersonlist, #joketext, #coolkidstitle{
        font-family: "Comic Sans MS", "Comic Sans", cursive;
        margin: 1rem;
    }
    #coolkidstitle {
        font-size: 3rem;
    }
    
</style>

// src/routes/coolpeople/+page.svelte


<div id="coolpeoplecontainer">
    <div id="coolpeople">
        <h1 id="coolkidstitle">COOL KIDS LIST</h1>
        <p class="opacity-70" id="coolpeopledesc">a list of people that have helped in the making of this website (or they're just that cool)</p>
        <ul>
            <li class="coolpersonlist" id="0">Ethan Edwards - came up with the idea for this website</li>
            <li class="coolpersonlist" id="1">Jacob Jackson - Various QOL ideas</li>
            <li class="coolpersonlist" id="2">Easton Snow - identified mobile bug for this very page</li>
            <li class="coolpersonlist" id="3">Isaiah Williams - idea of calendar widget</li>
            <li class="coolpersonlist" id="3">Henry Panning - I forgot why I added him here but he was here at some point</li>
        </ul>
    </div>
<p id="joketext" class="opacity-25">this list is all inclusive. if ur not on it, im sorry for your loss.</p>
<p id="joketext">not affiliated with LCPS or Tuscarora but that'd be pretty cool if I was.
   </p><p id="joketext">  also yes I realize that this page didn't exist for like 7 months randomly, but hey now it's back!</p>
<!-- <p></p> -->
</div>

<style>
       #coolpeople {
        /* font-family:'Courier New', Courier, monospace; */
        display: flex;
        justify-content: center;
        flex-direction: column;
        align-items: center;
    }
    #joketext {
        text-align: center;
    }
    #coolpeopledesc, .coolpersonlist, #joketext, #coolkidstitle{
        /* font-family:Arial, Helvetica, sans-serif; */
        /* font-family: Haettenschweiler, 'Arial Narrow Bold', sans-serif; */
        font-family: "Comic Sans MS", Arial;
        margin: 1rem;
    }
    #coolkidstitle {
        font-size: 3rem;
    }
</style>
